apiVersion: v1
kind: Service
metadata:
  name: online-shop-service
  namespace: hemant
spec:
  selector:
    app: online-shop
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30932
  type: NodePort
  
