apiVersion: v1
kind: Service
metadata:
  name: chai-app-service
  namespace: hemant
spec:
  selector:
    app: chai-app
  ports:
  - port: 3000
    targetPort: 80
    nodePort: 30933
    protocol: TCP
  type: NodePort
